service: backend-btg


provider:
  name: aws
  runtime: nodejs16.x
  architecture: arm64
  stage: production
  region: us-east-2
  memorySize: 2048
  logRetentionInDays: 1
  timeout: 15
  

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi:
          method: ANY
          path: /api/v1/{proxy+}

plugins:
  - serverless-jetpack
  - serverless-offline